#+EXPORT_FILE_NAME: ../README.md
#+OPTIONS: toc:1 |:t ^:nil tags:nil
#+TITLE: thruster-firmware
#+AUTHOR: Peter Polidoro
#+EMAIL: peter@polidoro.io

# Place warning at the top of the exported file
#+BEGIN_EXAMPLE
<!-- This file is generated automatically from metadata -->
<!-- File edits may be overwritten! -->
#+END_EXAMPLE

* Library Information
- Name :: thruster-firmware
- Version :: 0.1.0
- License :: GPLv3
- URL :: https://github.com/mechatronicmagic/thruster-firmware
- Author :: Peter Polidoro
- Email :: peter@polidoro.io
- PCB :: https://github.com/mechatronicmagic/thruster-pcb

** Description

Firmware for the thruster-pcb.

* Host Computer Setup

** Download this repository

[[https://github.com/mechatronicmagic/thruster-firmware.git]]

#+BEGIN_SRC sh
git clone https://github.com/mechatronicmagic/thruster-firmware.git
#+END_SRC

** PlatformIO

*** Install PlatformIO Core

[[https://docs.platformio.org/en/latest/core/installation/index.html]]

#+BEGIN_SRC sh
python3 -m venv .venv
source .venv/bin/activate
pip install pip --upgrade
pip install platformio
pio --version
#+END_SRC

*** 99-platformio-udev.rules

Linux users have to install udev rules for PlatformIO supported boards/devices.

**** Download udev rules file to /etc/udev/rules.d

#+BEGIN_SRC sh
curl -fsSL https://raw.githubusercontent.com/platformio/platformio-core/develop/platformio/assets/system/99-platformio-udev.rules | sudo tee /etc/udev/rules.d/99-platformio-udev.rules
#+END_SRC

**** Restart udev management tool

#+BEGIN_SRC sh
sudo service udev restart
#+END_SRC

**** Add user to groups

#+BEGIN_SRC sh
sudo usermod -a -G dialout $USER && sudo usermod -a -G plugdev $USER
#+END_SRC

**** Remove modemmanager

#+BEGIN_SRC sh
sudo apt-get purge --auto-remove modemmanager
#+END_SRC

**** After setting up rules and groups

You will need to log out and log back in again (or reboot) for the user group changes to take effect.

After this file is installed, physically unplug and reconnect your board.

*** Compile the firmware

**** Gnu/Linux

#+BEGIN_SRC sh
make firmware
#+END_SRC

**** Other

#+BEGIN_SRC sh
pio run -e feather
#+END_SRC

*** Upload the firmware

**** Gnu/Linux

#+BEGIN_SRC sh
make upload
#+END_SRC

**** Other

#+BEGIN_SRC sh
pio run -e feather -t upload
#+END_SRC

*** Serial Terminal Monitor

**** Gnu/Linux

#+BEGIN_SRC sh
make monitor
#+END_SRC

**** Other

#+BEGIN_SRC sh
pio device monitor --echo --eol=LF
#+END_SRC

